#+TITLE: GeHoJerez

This is a simple MPM code write in C, the main purpose of this code is to understand the basics concepts of a MPM code. I also write this lines to keep some order in my ideas during this crazy years. 

Miguel Molinos Pérez, PhD candidate. Madrid 28-5-2019

* Physical problem

** Balance of momentum (Equilibrium)

\begin{equation}
\rho \cdot \partial_{t} v + \partial_{x} \sigma =  \rho \cdot b
\end{equation}



** Compatibility 
** Constitutive response

\begin{equation}
\sigma = 2G\epsilon + \lambda tr(\epsilon) I
\end{equation}

* Material Point Method 
  
** Explicit MPM Scheme

1. Calculate the grid nodal mass and momentum by maping the particle mass and momentum to the corresponding grid nodes.
\begin{equation}
m_{I}^{k} = \sum^{n_p}_{p=1} m_p N_{Ip}^{k}
\end{equation} 
\begin{equation}
p_{I,i}^{k-1/2} = \sum^{n_p}_{p=1} m_p v_{ip}^{k-1/2}N_{Ip}^{k}
\end{equation}
1. Impose essential boundary conditions on the grid nodal momentum. At the fixed boundary, set $p_{iI}^{k-1/2} = 0$.
2. For the USF only, calculate the particle strain increment $\Delta \epsilon_{ijp}^{k-1/2}$, and the update the particle density and stress as follows:
   + Calculate the grid nodal velocity $v_{iI}^{k-1/2}$
     \begin{equation}
     v_{iI}^{k-1/2} = \frac{p_{iI}^{k-1/2}}{m_I^k}
     \end{equation}
   + Calculate the particle strain increment $\Delta \epsilon_{ijp}^{k-1/2}$ with :
     \begin{equation}
     \Delta \epsilon_{ijp}^{k-1/2} = \frac{1}{2}(N_{Ip,j}^{k} v_{iI}^{k-1/2} + N_{Ip,i}^{k} v_{jI}^{k-1/2})
     \end{equation}
   + Update the particle density with :
     \begin{equation}
     \rho_p^{k+1} = \frac{\rho_p^k}{1 + \Delta\epsilon_{iip}^{k-1/2}}
     \end{equation}
   + Update the particle stress stated based on $\Delta_{ijp}^{k-1/2}$ with an appropriate constitutive law.

* Proposed tests

** Simple propagation of a shock wave in a 1D media 

Here we solve the transport equation with a time integrator called Two-Step Taylor-Galerkin that stabilize the solution avoiding the formation of spurious oscillations during the transport. For the spatial discretization will be used 1D li

 \partial_{t} u + c \cdot \partial_{x} u = 0

The algorithm is as follows : 
1. Transfer information to the Gauss-Points :  u^{n}_{GP} = \sum^{N}_{i=0}N(x_i) \cdot u^{n}_{i}
2. Get the solution in the Gauss-Points for t = n + 1/2 : u^{n+1/2}_{GP} = u^{n}_{GP} - \Delta t/2 \cdot \sum^{N}_{i=0} \partial N(x_i) \cdot u^{n}_{i}
3. Get the solution in the nodes for t = n + 1 : 

** Simple propagation of a shock wave in a 1D elastic media using the formulation \sigma - v


* Items

** DONE Get the Nodal coordinates of the material points

*** 23-05-2019, Madrid
    
** DONE Get the strain increment in the material points

*** 28-05-2019, Madrid
** DONE Get the stress state
