# GeHoJerez

This is a simple MPM code write in C, the main purpose of this code is to understand the basics concepts of a MPM code. I also write this lines to keep some order in my ideas during this crazy years. 

Miguel Molinos Pérez, PhD candidate. Madrid 28-5-2019

* Physical problem

** Balance of momentum (Equilibrium)

\rho \cdot \partial_{t} v + \partial_{x} \sigma =  \rho \cdot b

** Compatibility


** Constitutive response

\sigma = 2G\Epsilon + \lambda tr(\Epsilon) I

   
* Material Point Method 


* Proposed tests

** Simple propagation of a shock wave in a 1D media 

Here we solve the transport equation with a time integrator called Two-Step Taylor-Galerkin that stabilize the solution avoiding the formation of spurious oscillations during the transport. For the spatial discretization will be used 1D li

 \partial_{t} u + c \cdot \partial_{x} u = 0

The algorithm is as follows : 
1. Transfer information to the Gauss-Points :  u^{n}_{GP} = \sum^{N}_{i=0}N(x_i) \cdot u^{n}_{i}
2. Get the solution in the Gauss-Points for t = n + 1/2 : u^{n+1/2}_{GP} = u^{n}_{GP} - \Delta t/2 \cdot \sum^{N}_{i=0} \partial N(x_i) \cdot u^{n}_{i}
3. Get the solution in the nodes for t = n + 1 : 

** Simple propagation of a shock wave in a 1D elastic media using the formulation \sigma - v


* Items

** DONE Get the Nodal coordinates of the material points

*** 23-05-2019, Madrid

** Get the strain increment in the material points

*** 28-05-2019, Madrid
