#+TITLE: GeHoJerez
#+AUTHOR: Miguel Molinos Pérez
#+EMAIL: m.molinos AT outlook DOT com

This is a simple MPM code write in C, the main purpose of this code is to understand the basics concepts of a MPM code. 
I also write this lines to keep some order in my ideas during this crazy years. 

[[mailto:m.molinos@outlook.es][Miguel Molinos Pérez]], PhD candidate [fn:1]. Madrid 28-5-2019


- [[file:Introduction/Introduction.org][Introduction]]

- [[file:Governing_Equations/Governing_Equations.org][Governing Equations]]

- [[file:Material_Point_Method/Material_Point_Method.org][Material Point Method ]] 

  
* Constitutive response
  
** Elastic material 
\begin{equation}
\sigma = 2G\epsilon + \lambda tr(\epsilon) I
\end{equation}

** Visco-elastic material   
   
Viscoelastic fluids exhibit both viscous and elastic behaviour when
subjected to deformation. Therefore these materials are governed by
the Navier-Stokes equations enriched with an extra *elastic* stress
$\mathbf{\tau}_p$
\begin{equation}
\rho\left[\partial_t\mathbf{u}+\nabla\cdot(\mathbf{u}\otimes\mathbf{u})\right] = 
- \nabla p + \nabla\cdot(2\mu_s\mathbf{D}) + \nabla\cdot\mathbf{\tau}_p
+ \rho\mathbf{a}
\end{equation}
where $\mathbf{D}=[\nabla\mathbf{u} + (\nabla\mathbf{u})^T]/2$ is the
deformation tensor and $\mu_s$ is the solvent viscosity of the
viscoelastic fluid.


* Proposed tests

** Simple propagation of a shock wave in a 1D media 

Here we solve the transport equation with a time integrator called Two-Step Taylor-Galerkin that stabilize the solution avoiding the formation of spurious oscillations during the transport. For the spatial discretization will be used 1D li

 \partial_{t} u + c \cdot \partial_{x} u = 0

The algorithm is as follows : 
1. Transfer information to the Gauss-Points :  u^{n}_{GP} = \sum^{N}_{i=0}N(x_i) \cdot u^{n}_{i}
2. Get the solution in the Gauss-Points for t = n + 1/2 : u^{n+1/2}_{GP} = u^{n}_{GP} - \Delta t/2 \cdot \sum^{N}_{i=0} \partial N(x_i) \cdot u^{n}_{i}
3. Get the solution in the nodes for t = n + 1 : 

** Simple propagation of a shock wave in a 1D elastic media using the formulation \sigma - v
   

* Items

** DONE Get the Nodal coordinates of the material points

*** 23-05-2019, Madrid
    
** DONE Get the strain increment in the material points

*** 28-05-2019, Madrid
** DONE Get the stress state
   

* Codes 

#+BEGIN_SRC C
fprintf("Hola mundo \n");
#+END_SRC 


* Biblio and footnotes
  
[fn:1] [[https://www.researchgate.net/profile/Miguel_Molinos_Perez][ResearcheGate Profile]]  
